import Head from 'next/head'
import { ThemeProvider, BaseStyles, Box, SSRProvider } from '@primer/react'
import ColorModeSwitcher from '@/components/ColorModeSwitcher'
import '@/styles/reset.css'
import Highcharts from 'highcharts'

if (typeof Highcharts === 'object') {
    require('highcharts/modules/accessibility')(Highcharts)
}

export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Next.js Primer Template</title>
                <meta
                    name="description"
                    content="Generated by the Primer Next.js template"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SSRProvider>
                <ThemeProvider colorMode="auto" preventSSRMismatch>
                    <BaseStyles>
                        <Box
                            backgroundColor={'canvas.inset'}
                            minHeight={'100vh'}
                            width={'100vw'}
                            position={'absolute'}
                            top={0}
                            left={0}
                        >
                            <Component {...pageProps} />
                        </Box>
                        <ColorModeSwitcher />
                    </BaseStyles>
                </ThemeProvider>
            </SSRProvider>
        </>
    )
}
