import Head from 'next/head'
import { ThemeProvider, BaseStyles, Box } from '@primer/react'
import ColorModeSwitcher from '@/components/ColorModeSwitcher'
import '@/styles/reset.css'

export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Next.js Primer Template</title>
                <meta
                    name="description"
                    content="Generated by the Primer Next.js template"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ThemeProvider colorMode="auto" preventSSRMismatch>
                <BaseStyles>
                    <Box
                        backgroundColor={'canvas.default'}
                        height={'100vh'}
                        width={'100vw'}
                        position={'absolute'}
                        top={0}
                        left={0}
                    >
                        <Component {...pageProps} />
                    </Box>
                    <ColorModeSwitcher />
                </BaseStyles>
            </ThemeProvider>
        </>
    )
}
